# Generated by Django 3.2.9 on 2021-11-13 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(default=datetime.datetime(2021, 11, 13, 14, 14, 44, 439115, tzinfo=utc), upload_to='media/posts/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 11, 13, 14, 14, 53, 675611, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
